env: "local"
log_level: "info"
log_type: "text" # 'text' or 'json'. Text type has colorized error levels
service_name: "rule-api"
port: "8081"
version: "1.0.0"
cors_max_age_hours: "24h"
rule_api_url_path: "/rule/v1"
max_body_size: 2 # Max MB size for request body
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" # User agent for /robots.txt requests.

cache:
  servers: "cache:11211"
  ttl_for_robots_txt: "24h"

database:
  host: "db"
  port: "5432"
  user: "web_crawler_rw_user"
  password: "test"
  name: "web_crawler_rds_psql"
  conn_max_lifetime: "10m"
  max_open_conns: 10
  max_idle_conns: 10

http_client:
  request_timeout: "15s"
  max_idle_connections: 800
  max_idle_connections_per_host: 10
  max_connections_per_host: 10 # good to have it the same as a cache. Threshold in url-gate-worker
  idle_connection_timeout: "15s"
  tls_handshake_timeout: "10s"
  dial_timeout: "10s"
  dial_keep_alive: "20s"
  tls_insecure_skip_verify: false # If true - the client will not verify the server's certificate

telemetry:
  enabled: true
  collector_url: "localhost:4318"
