// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/crawl-allowed": {
            "get": {
                "description": "Check if the given user agent is allowed to crawl the specified URL based on the robots.txt rules",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Crawling"
                ],
                "summary": "Check if crawling is allowed for a specific user agent and URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL to check",
                        "name": "url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User agent to check",
                        "name": "user_agent",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response object",
                        "schema": {
                            "$ref": "#/definitions/model.AllowedCrawlResponse"
                        }
                    }
                }
            }
        },
        "/custom-rule": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a custom rule based on the provided query parameter 'id' or 'url'",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Custom Rule"
                ],
                "summary": "Get custom rule by ID or URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Custom rule ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Custom rule URL",
                        "name": "url",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Custom rule object",
                        "schema": {
                            "$ref": "#/definitions/model.Rule"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing custom rule based on the provided ID or URL.",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Custom Rule"
                ],
                "summary": "Update a custom rule by ID or URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Custom rule ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Custom rule URL",
                        "name": "url",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Block the domain from being crawled",
                        "name": "blocked",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Updated custom rule file content",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated custom rule",
                        "schema": {
                            "$ref": "#/definitions/model.Rule"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new custom rule by providing a URL and the corresponding rule file",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Custom Rule"
                ],
                "summary": "Create a custom rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL for the custom rule",
                        "name": "url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Block the domain from being crawled",
                        "name": "blocked",
                        "in": "query"
                    },
                    {
                        "description": "Custom rule file content",
                        "name": "file",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Custom rule created successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete an existing custom rule based on the provided ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Custom Rule"
                ],
                "summary": "Delete a custom rule by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Custom rule ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Rule deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AllowedCrawlResponse": {
            "description": "Is crawl allowed for the domain",
            "type": "object",
            "properties": {
                "blocked": {
                    "type": "boolean"
                },
                "error": {
                    "type": "string"
                },
                "is_allowed": {
                    "type": "boolean"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "model.Rule": {
            "description": "Represents a custom rule for a domain",
            "type": "object",
            "properties": {
                "blocked": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "robots_txt": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
